# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Startup in Storm Lake 2021
#email: backman@bvu.edu
description: > # this means to ignore newlines until "baseurl:"
  BVU Computer Science
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://startup-in-storm-lake-2021.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  nathan-backman

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
